import { Formulario } from "src/app/shared/data/models/formulario.model";

export const formularioInformacionSeguimiento: Formulario = {
  campos: [
    {
      nombre: "no_auditoria",
      descripcion: "No de Auditoría",
      etiqueta: "No de Auditoría",
      icono: "format_list_numbered",
      tipo: "number",
      placeholder: "Número de auditoría",
      deshabilitado: true,
      validaciones: [{ tipo: "requerido", valor: "" }],
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "tipo",
      etiqueta: "Tipo",
      icono: "list",
      tipo: "select",
      parametros: {
        urlParametros:
          "parametro?query=TipoParametroId:140&fields=Id,Nombre&limit=0",
      },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-2 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "proceso",
      etiqueta: "Macroproceso, Proceso o Dependencia",
      icono: "work",
      tipo: "select",
      parametros: {
        opciones: [
          { Id: "1", Nombre: "Macroproceso" },
          { Id: "2", Nombre: "Proceso" },
          { Id: "3", Nombre: "Dependencia" },
        ],
      },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-6 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "lider",
      etiqueta: "Líder",
      icono: "person",
      tipo: "text",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "responsable",
      etiqueta: "Responsable",
      icono: "supervisor_account",
      tipo: "text",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "fecha_emision_informe",
      etiqueta: "Fecha Emisión de Informe",
      icono: "event",
      parametros: {
        vista: "year",
        fecha_inicio: "2024-01-01T05:00:00.000Z",
      },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: false,
      tipo: "date",
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "objetivo_auditoria",
      etiqueta: "Objetivo de la Auditoría",
      icono: "flag",
      tipo: "textarea",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
    {
      nombre: "alcance_auditoria",
      etiqueta: "Alcance de la Auditoría",
      icono: "visibility",
      tipo: "textarea",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
    {
      nombre: "criterios",
      etiqueta: "Criterios",
      icono: "check_circle",
      tipo: "textarea",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
    {
      nombre: "muestra",
      etiqueta: "Muestra",
      icono: "assignment",
      descripcion: "En caso de no aplicar se debe indicar (N/A)",
      tipo: "textarea",
      validaciones: [{ valor: "" }],
      placeholder: "En caso de no aplicar se debe indicar (N/A)",
      deshabilitado: false,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
  ],
};
