import { Formulario } from "src/app/shared/data/models/formulario.model";
import { environment } from "src/environments/environment";

export const formularioInformacionAuditoria: Formulario = {
  campos: [
    {
      nombre: "no_auditoria",
      descripcion: "No Auditoría y/o seguimiento",
      etiqueta: "No Auditoría y/o seguimiento",
      icono: "format_list_numbered",
      tipo: "number",
      placeholder: "Escriba aquí el número de la auditoría",
      deshabilitado: true,
      validaciones: [{ tipo: "requerido", valor: "" }],
      claseGrid: "col-lg-3 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "macroproceso",
      etiqueta: "Macroproceso",
      icono: "account_tree",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "proceso",
      etiqueta: "Proceso",
      icono: "account_tree",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-5 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "dependencia",
      etiqueta: "Dependencia",
      icono: "apartment",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-6 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "jefe_nombre",
      etiqueta: "Jefe dependencia",
      icono: "person",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-6 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "asistente_nombre",
      etiqueta: "Asistente dependencia",
      icono: "supervisor_account",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "correo_dependencia",
      etiqueta: "Correo Dependencia",
      icono: "email",
      tipo: "email",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "jefe_correo",
      etiqueta: "Correo Jefe dependencia",
      icono: "email",
      tipo: "email",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "asistente_correo",
      etiqueta: "Correo Asistente dependencia",
      icono: "email",
      tipo: "email",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "correo_complementario",
      etiqueta: "Correo Complementario",
      icono: "email",
      tipo: "email",
      validaciones: [{ tipo: "email", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "fecha_emision",
      etiqueta: "Fecha de Emisión Informe",
      icono: "event",
      parametros: {
        vista: "year",
        fecha_inicio: "2024-01-01T05:00:00.000Z",
      },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: false,
      tipo: "date",
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "objetivo_auditoria",
      etiqueta: "Objetivo de la Auditoría",
      icono: "flag",
      tipo: "textarea",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
    {
      nombre: "alcance_auditoria",
      etiqueta: "Alcance de la Auditoría",
      icono: "visibility",
      tipo: "textarea",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
    {
      nombre: "criterios",
      etiqueta: "Criterios",
      icono: "check_circle",
      tipo: "textarea",
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
    {
      nombre: "muestra",
      etiqueta: "Muestra",
      icono: "assignment",
      descripcion: "En caso de no aplicr se debe indicar (N/A)",
      tipo: "textarea",
      validaciones: [{ valor: "" }],
      placeholder: "En caso de no aplicar se debe indicar (N/A)",
      deshabilitado: false,
      claseGrid: "col-lg-12 col-md-12 col-sm-12 col-xs-12",
    },
  ],
};
