import { Formulario } from "src/app/shared/data/models/formulario.model";
import { environment } from "src/environments/environment";

export const formularioInformacionAuditoria: Formulario = {
  campos: [
    {
      nombre: "titulo_aduitoria",
      descripcion: "Titulo de Auditoría",
      etiqueta: "Titulo de Auditoría",
      icono: "assignment",
      tipo: "text",
      placeholder: "Escriba aquí el titulo de la auditoría",
      deshabilitado: false,
      validaciones: [{ tipo: "requerido", valor: "" }],
      claseGrid: "col-lg-7 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "origen_auditoria",
      etiqueta: "Origen Auditoría",
      icono: "flag",
      tipo: "select",
      parametros: {
        urlParametros:
          "parametro?query=TipoParametroId:161&fields=Id,Nombre&limit=0",
      },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: false,
      claseGrid: "col-lg-5 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "macroproceso",
      etiqueta: "Macroproceso",
      icono: "account_tree",
      tipo: "select",
      parametros: {
        urlParametros: `parametro?query=TipoParametroId:${environment.INFO_AUDITORIA.TIPOS_PROCESO.VALORES.MACROPROCESO.TIPO_PARAMETRO_ID}&fields=Id,Nombre&limit=0&sortby=Nombre&order=asc`,
        opciones: [],
      },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: false,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "proceso",
      etiqueta: "Proceso",
      icono: "account_tree",
      tipo: "select",
      parametros: { opciones: [] },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "dependencia",
      etiqueta: "Dependencia",
      icono: "apartment",
      tipo: "select",
      parametros: { opciones: [] },
      validaciones: [{ tipo: "requerido", valor: "" }],
      deshabilitado: false,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "jefe_nombre",
      etiqueta: "Jefe dependencia",
      icono: "person",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-6 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "asistente_nombre",
      etiqueta: "Asistente dependencia",
      icono: "supervisor_account",
      tipo: "text",
      deshabilitado: true,
      claseGrid: "col-lg-6 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "correo_dependencia",
      etiqueta: "Correo Dependencia",
      icono: "email",
      tipo: "email",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "jefe_correo",
      etiqueta: "Correo Jefe dependencia",
      icono: "email",
      tipo: "email",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "asistente_correo",
      etiqueta: "Correo Asistente dependencia",
      icono: "email",
      tipo: "email",
      deshabilitado: true,
      claseGrid: "col-lg-4 col-md-6 col-sm-12 col-xs-12",
    },
    {
      nombre: "correo_complementario",
      etiqueta: "Correo Complementario",
      icono: "email",
      tipo: "email",
      validaciones: [{ tipo: "email", valor: "" }],
      deshabilitado: false,
      claseGrid: "col-lg-6 col-md-6 col-sm-12 col-xs-12",
    },
  ],
};
